name: build
on:
  workflow_call
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: |
          pnpm install
          pnpm gulp vscode-min
      - run: |
          ls -lh out-packages
  build-darwin:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: |
          pnpm install
          pnpm gulp vscode-min
      - run: |
          ls -lh out-packages
  build-win32:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: |
          pnpm install
          pnpm gulp vscode-min
      - run: |
          ls -lh out-packages
